config/routes.rb
Notebook::Application.routes.draw do
  devise_for :users
  root "home#index"
  get '/profiles/dashboard' => 'profiles#dashboard', :as => :edit_profile_root
  resources :profiles, :only => [:dashboard]
  get '/:locale' => 'home#index'
  scope '/:locale' do
  
  resources :tasks 
  resources :contacts 
  resources :notesections do
    resources :notepages
  end
  resources :todosections do
    resources :todopages do
      resources :tasks   do
        put :st, as: 'st'
        put :sti, as: 'sti'
        put :ust, as: 'ust'
        put :usti, as: 'usti'
      end 
    end
  end 
end
  

  

end

app/models/notepage.rb
class Notepage < ActiveRecord::Base
  belongs_to :notesection
  validates :title, presence: true
  validates :notesection_id, presence: true
end

app/controllers/notepages_controller.rb
class NotepagesController < ApplicationController
	def index
    @notepages = Notepage.where(notesection_id: @notesection.id)
  end
  
  def new
    @notesection = Notesection.find(params[:notesection_id])
    @notepage = Notepage.new(notepage_params)
    @notepage.notesection_id = @notesection.id
    render 'new'
  end
  def show
    @notesection = Notesection.find(params[:notesection_id])
    @notepages = Notepage.where(notesection_id: @notesection.id)
    @notepage = Notepage.find(params[:id])
  end


  def create
    @notesection = Notesection.find(params[:notesection_id])
    @notepage = Notepage.new(notepage_params)
    @notepage.notesection_id = @notesection.id
    if @notepage.save
      redirect_to @notesection
    else
      @error=t("Title can't be blank")
      render 'new'
    end
  end

  def edit
    @notesection = Notesection.find(params[:notesection_id])
    @notepage = Notepage.find(params[:id])
  end

  def update
    @notesection = Notesection.find(params[:notesection_id])
    @notepage = Notepage.find(params[:id])
    @notepage.update_attributes(notepage_params)
    if @notepage.update(notepage_params)
      redirect_to  @notesection
    else
      @error=t("Title can't be blank")
      render 'edit'
    end
  end
  
  def destroy
    @notesection = Notesection.find(params[:notesection_id])
    @notepage = @notesection.notepages.find(params[:id])
    @notepage.destroy
    redirect_to notesection_path(@notesection)
  end

  private
    def notepage_params
      params.require(:notepage).permit(:title, :description)
    end
end

app/helpers/notepages_helper.rb
module NotepagesHelper
end

app/views/notepages/_form.html.haml
= form_for([@notesection, @notesection.notepages.build]) do |f|
  %p
    = f.label I18n.t("Title Pages")
    = f.text_field :title
    %br
    = f.submit I18n.t("Create")

app/views/notepages/_notepage.html.haml
.page.word-break
  %table
    %tr#head
      %th
        #title 
          #{notepage.title}
          = link_to image_tag("ed.png", :border => 0),  edit_notesection_notepage_path(@notesection,[notepage])
          = link_to image_tag("del.png", :border => 0),  [notepage.notesection, notepage],  method: :delete, data:  { confirm: I18n.t("Are you sure?") }    
    %tr
      %td #{notepage.description}
%br

app/views/notepages/edit.html.haml
.e_form.big
  #title
    =t("EditP")
    %br
    =t("Pagee")
  = form_for :notepage, url: notesection_notepage_path, method: :patch do |f|
    - if @notepage.errors.any?
      #error_explanation
        = @error
    %p
      = f.label I18n.t("Title Page")
      = f.text_field :title
      %br
      = f.label "Description Page"
      = f.text_area :description 
      %br
      = f.submit I18n.t("Update")
  
  %space <-
  = link_to I18n.t("Back"),@notesection

app/views/notepages/new.html.haml
.e_form.big
  #title
    =t("New Page")
  - if @notepage.errors.any?
    #error_explanation
      = @error
  = render 'form'
  %br
  %space <-
  = link_to I18n.t("Back to Section"), @notesection

app/views/notepages/show.html.haml
%br
%br
%br
.page.word-break
	%table
		%tr#head
			%td
				#title 
					= link_to image_tag("comeback.png", :border => 0),@notesection
					#{@notepage.title}
					= link_to image_tag("ed.png", :border => 0),  edit_notesection_notepage_path(@notesection,@notepage)
					= link_to image_tag("del.png", :border => 0),  [@notepage.notesection, @notepage],  method: :delete, data:  { confirm: I18n.t("Are you sure?") }
	
	%tr#section_id
		%td#name
			#{@notepage.description}     