config/routes.rb
Notebook::Application.routes.draw do
  devise_for :users
  root "home#index"
  get '/profiles/dashboard' => 'profiles#dashboard', :as => :edit_profile_root
  resources :profiles, :only => [:dashboard]
  get '/:locale' => 'home#index'
  scope '/:locale' do
  
  resources :tasks 
  resources :contacts 
  resources :notesections do
    resources :notepages
  end
  resources :todosections do
    resources :todopages do
      resources :tasks   do
        put :st, as: 'st'
        put :sti, as: 'sti'
        put :ust, as: 'ust'
        put :usti, as: 'usti'
      end 
    end
  end 
end
  

  

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :todopage
  belongs_to :user
  validates :title, presence: true
  validates :todopage_id, presence: true

  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
    @task = Task.new
    @tasks=Task.where(user_id: current_user.id)
    @utasks = []
    @ftasks = []
    @ttasks = []
    @tasks.each do |t|
      @utasks << t if t.urgency_status=true
      @ftasks << t if t.execution_status=false
      @ttasks << t if t.execution_status=true
    end      
    @tcount = @ttasks.count
    @ucount = @utasks.count
    @fcount = @ftasks.count

    @todopages = Todopage.all
  end

  def create
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:todopage_id])
    @task = Task.new(task_params)
    @task.execution_status = false
    @task.urgency_status = false
    @task.user_id = current_user.id
    @task.todopage_id = @todopage.id
    tasks = Task.find_all_by_todopage_id(@task.todopage_id)
    if @task.save
      redirect_to @todosection
    else
      @error=t("Title can't be blank")
      render 'new'
    end
  end

  def destroy
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:todopage_id])
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to @todosection
  end
  
  def show
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:todopage_id])
    @task = Task.find(params[:id])
  end

  def edit
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:todopage_id])
    @task = Task.find(params[:id])
  end

  def update
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:todopage_id])
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    if @task.update(task_params)
      redirect_to @todosection
    else
      @error=t("Title can't be blank")
      render 'edit'
    end
  end

  def st
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:todopage_id])
    @task = Task.find(params[:task_id])

    @id = params[:id]
    @task.execution_status = !@task.execution_status
    @task.save
    redirect_to @todosection
  end
  
  def sti



    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:todopage_id])
    @task = Task.find(params[:task_id])
    @task.execution_status = !@task.execution_status
    @task.save
    @tasks=Task.where(user_id: current_user.id)
    @utasks = []
    @ftasks = []
    @ttasks = []
    @tasks.each do |t|
      @utasks << t if t.urgency_status=true
      @ftasks << t if t.execution_status=false
      @ttasks << t if t.execution_status=true
    end      
    @tcount = @ttasks.count
    @ucount = @utasks.count
    @fcount = @ftasks.count
    render "index" 
  end
  def ust
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:todopage_id])
    @task = Task.find(params[:task_id])
    @task.urgency_status = !@task.urgency_status
    @task.save
    redirect_to @todosection
  end
    def usti
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:todopage_id])
    @task = Task.find(params[:task_id])
    @task.urgency_status = !@task.urgency_status
    @task.save
    @tasks=Task.where(user_id: current_user.id)
    @utasks = []
    @ftasks = []
    @ttasks = []
    @tasks.each do |t|
      @utasks << t if t.urgency_status=true
      @ftasks << t if t.execution_status=false
      @ttasks << t if t.execution_status=true
    end      
    @tcount = @ttasks.count
    @ucount = @utasks.count
    @fcount = @ftasks.count
    render "index"  
  end

  
  private
    def task_params
      params.require(:task).permit(:execution_status, :title, :description, :urgency_status, :completion_date)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for([@todosection, @todopage, @todopage.tasks.build]) do |f|
  = f.label I18n.t("Title Task")
  = f.text_field :title
  = f.label I18n.t("Description Task")
  = f.text_field :description
  %br
  = f.check_box :execution_status
  =I18n.t("Executed")
  = f.check_box :urgency_status
  =I18n.t("Urgently")
  =I18n.t("Execute Until")
  = f.date_field :completion_date
  %br
  = f.submit I18n.t("Create")
  %br
  %space <-
  = link_to I18n.t("Back"),@todosection
  

app/views/tasks/_task.html.haml
.notes
  %table
    %td#chek
      = link_to check_box_tag('execution_status', 'execution_status', task.execution_status) , todosection_todopage_task_st_path(@todosection.id,task.todopage_id,task.id), controller: :tasks,method: :put 
    %td#name
      #{task.title}
      .descr
        #{task.description}
    %td#urgency
      = link_to check_box_tag('urgency_status', 'urgency_status', task.urgency_status) , todosection_todopage_task_ust_path(@todosection.id,task.todopage_id,task.id), controller: :tasks,method: :put 
    %td#date
      #{task.completion_date}
    %td#hrefs
      = link_to image_tag("edt.png", :border => 0), edit_todosection_todopage_task_path(task.todopage.todosection,task.todopage,task) 
      = link_to image_tag("delt.png",:border => 0), [task.todopage.todosection, task.todopage, task],  method: :delete, data: { confirm: I18n.t("Are you sure?") }

app/views/tasks/_th.html.haml
%th#chek 
  =I18n.t("Executed")
%th#name 
  =I18n.t("Title")
%th#urgency 
  =I18n.t("Urgently")
%th#date 
  =I18n.t("Execute Until")
%th#hrefs 

app/views/tasks/edit.html.haml
.e_form
  #title
    =t("EditN")
    %br
    =t("Taske")
  = form_for :task, url: todosection_todopage_task_path, method: :patch do |f|
    - if @task.errors.any?
      #error_explanation
        = @error
    = f.label I18n.t("Title Task")
    = f.text_field :title
    = f.label I18n.t("Description Task")
    = f.text_field :description
    %br
    = f.check_box :execution_status
    Execution status
    = f.check_box :urgency_status
    Urgency status
    Completion date
    = f.date_field :completion_date
    %br
    = f.submit I18n.t("Update")
    %br
    %space <-
    = link_to I18n.t("Back"),@todosection

app/views/tasks/index.html.haml
%br
.page.note_index.task_index
  %table
    %tr
      .head
        #title 
          =I18n.t("Urgent Task")
          ( #{@ucount} )
    =render "th"
    - @utasks.each  do |ut|
      %tr
        %td#chek
          = link_to check_box_tag('execution_status', 'execution_status', ut.execution_status) , todosection_todopage_task_sti_path(ut.todopage.todosection.id,ut.todopage_id,ut.id), controller: :tasks,method: :put 
        %td#name.left       
          .ttitle
            = ut.title
            (#{ut.todopage.title})
          .descr
            = ut.description
        %td#urgency
          = link_to check_box_tag('urgency_status', 'urgency_status', ut.urgency_status) , todosection_todopage_task_usti_path(ut.todopage.todosection.id,ut.todopage_id,ut.id), controller: :tasks,method: :put 

        %td#date
          #{ut.completion_date}
        %td#hrefs
          = link_to image_tag("edt.png", :border => 0), edit_todosection_todopage_task_path(ut.todopage.todosection,ut.todopage,ut) 
          = link_to image_tag("delt.png",:border => 0), [ut.todopage.todosection, ut.todopage, ut],  method: :delete, data: { confirm: I18n.t("Are you sure?") }

.page.note_index.task_index
  %table
    %tr
      .head
        #title 
          =I18n.t("ToDo Tasks")
          ( #{@fcount} )
    =render "th"
    - @ftasks.each  do |ft|
      %tr
        %td#chek
          = link_to check_box_tag('execution_status', 'execution_status', ft.execution_status) , todosection_todopage_task_sti_path(ft.todopage.todosection.id,ft.todopage_id,ft.id), controller: :tasks,method: :put 
        %td#name.left        
          .ttitle
            = ft.title
            (#{ft.todopage.title})
          .descr
            = ft.description
        %td#urgency
          = link_to check_box_tag('urgency_status', 'urgency_status', ft.urgency_status) , todosection_todopage_task_usti_path(ft.todopage.todosection.id,ft.todopage_id,ft.id), controller: :tasks,method: :put 

        %td#date
          #{ft.completion_date}
        %td#hrefs
          = link_to image_tag("edt.png", :border => 0), edit_todosection_todopage_task_path(ft.todopage.todosection,ft.todopage,ft) 
          = link_to image_tag("delt.png",:border => 0), [ft.todopage.todosection, ft.todopage, ft],  method: :delete, data: { confirm: I18n.t("Are you sure?") }

.page.note_index.task_index
  %table
    %tr 
      .head
        #title 
          =I18n.t("Completed Tasks")
          ( #{@tcount} )
    =render "th"
    - @ttasks.each  do |tt|
      %tr
        %td#chek
          = link_to check_box_tag('execution_status', 'execution_status', tt.execution_status) , todosection_todopage_task_sti_path(tt.todopage.todosection.id,tt.todopage_id,tt.id), controller: :tasks,method: :put 
        %td#name.left      
          .ttitle
            = tt.title
            (#{tt.todopage.title})
          .descr
            = tt.description
        %td#urgency
          = link_to check_box_tag('urgency_status', 'urgency_status', tt.urgency_status) , todosection_todopage_task_usti_path(tt.todopage.todosection.id,tt.todopage_id,tt.id), controller: :tasks,method: :put 

        %td#date
          #{tt.completion_date}
        %td#hrefs
          = link_to image_tag("edt.png", :border => 0), edit_todosection_todopage_task_path(tt.todopage.todosection,tt.todopage,tt) 
          = link_to image_tag("delt.png",:border => 0), [tt.todopage.todosection, tt.todopage, tt],  method: :delete, data: { confirm: I18n.t("Are you sure?") }

app/views/tasks/new.html.haml
.e_form
  #title 
    =t("New Task")
  - if @task.errors.any?
    #error_explanation
      = @error
  = render 'form'