config/routes.rb
Notebook::Application.routes.draw do
  devise_for :users
  root "home#index"
  get '/profiles/dashboard' => 'profiles#dashboard', :as => :edit_profile_root
  resources :profiles, :only => [:dashboard]
  get '/:locale' => 'home#index'
  scope '/:locale' do
  
  resources :tasks 
  resources :contacts 
  resources :notesections do
    resources :notepages
  end
  resources :todosections do
    resources :todopages do
      resources :tasks   do
        put :st, as: 'st'
        put :sti, as: 'sti'
        put :ust, as: 'ust'
        put :usti, as: 'usti'
      end 
    end
  end 
end
  

  

end

app/models/todosection.rb
class Todosection < ActiveRecord::Base
  belongs_to :user
  has_many :todopages, dependent: :destroy
  validates :title, presence: true
  validates :user_id, presence: true
end

app/controllers/todosections_controller.rb
class TodosectionsController < ApplicationController
  def new
    @todosection = Todosection.new
  end

  def create
    @todosection = Todosection.new(todosection_params)
    @todosection.user_id = current_user.id
    if @todosection.save
      redirect_to todosections_path
    else
      @error=t("Title can't be blank")
      render 'new'
    end
  end
  
  def show
    @todosection = Todosection.find(params[:id])
    @todopage = Todopage.where(todosection_id: @todosection.id)
    @todopage.sort! { |a,b| a.title.downcase <=> b.title.downcase }
  end


  def index
    @todosection = Todosection.new
    @todosections = Todosection.where(user_id: current_user.id)
  end

  def edit
    @todosection = Todosection.find(params[:id])
  end

  def update
    @todosection = Todosection.find(params[:id])
    if @todosection.update(todosection_params)
      redirect_to todosections_path
    else
      @error=t("Title can't be blank")
      render 'edit'
    end
  end

  def destroy
    @todosection = Todosection.find(params[:id])
    @todosection.destroy
    redirect_to todosections_path
  end

  private
    def todosection_params
      params.require(:todosection).permit(:title)
    end
end

app/helpers/todosections_helper.rb
module TodosectionsHelper
end

app/views/todosections/_form.html.haml
= form_for @todosection do |f|
  %p
    = f.label I18n.t("Title Section")
    = f.text_field :title
    %br
    = f.submit I18n.t("Create")

app/views/todosections/edit.html.haml
.e_form
  #title
    =t("EditS")
    %br
    =t("Sectione")
  = form_for :todosection, url: todosection_path, method: :patch do |f|
    - if @todosection.errors.any?
      #error_explanation
        = @error
  = render 'form'
  %space <-
  = link_to I18n.t("Back to Sections"), todosections_path
  %br
  %space <-
  = link_to I18n.t("Back to Section"), todosection_path

app/views/todosections/index.html.haml
.add_form
  = form_for @todosection do |f|
    = f.label I18n.t("New Section")
    = f.text_field :title, placeholder: I18n.t("Title Section"), style: "margin-top:6px;border:1px #DEB887 solid "
    = f.submit I18n.t("Add")
.page.sections
  %table
    %tr#head
      %th
        #title
          =t("All Sections")
      %th
    - @todosections.each do |s|
      %tr#section_id
        %td#names
          = s.title
        %td#linkss
          = link_to image_tag("show.png", :border => 0), s
          = link_to image_tag("ed.png", :border => 0), edit_todosection_path(s)
          = link_to image_tag("del.png", :border => 0), todosection_path(s),    method: :delete, data: { confirm: I18n.t("Are you sure?") } 

app/views/todosections/new.html.haml
.e_form
  #title
    =t("New Section")
  - if @todosection.errors.any?
    #error_explanation
      = @error
  = render 'form'
  %br
  %space <-
  = link_to I18n.t("Back to Sections"), todosections_path

app/views/todosections/show.html.haml
.about
  #title #{@todosection.title}
  %space <-
  = link_to  I18n.t("Back to Sections"), todosections_path
  |
  = link_to  I18n.t("Edit Section"), edit_todosection_path(@todosection)
  %space ->
  %br
  =I18n.t("Open page")
  %select#page_select{name: "page_select", onchange: "document.location=this.options[this.selectedIndex].value"}
    %option ...
    - @todopage.each do |p|
      %option{value:"#{@todosection.id}/todopages/#{p.id}"}
        = p.title
.block
  .extremum-click.pb
    .pages_block 
      =I18n.t("See all pages")
      = image_tag("down.png", :border => 0)
  .extremum-slide 
    = render @todosection.todopages

.add_form
  = form_for([@todosection, @todosection.todopages.build]) do |f|
    = f.label I18n.t("New Page")
    = f.text_field :title,placeholder: I18n.t("Title Page")
    = f.submit I18n.t("Add")  