config/routes.rb
Notebook::Application.routes.draw do
  devise_for :users
  root "home#index"
  get '/profiles/dashboard' => 'profiles#dashboard', :as => :edit_profile_root
  resources :profiles, :only => [:dashboard]
  get '/:locale' => 'home#index'
  scope '/:locale' do
  
  resources :tasks 
  resources :contacts 
  resources :notesections do
    resources :notepages
  end
  resources :todosections do
    resources :todopages do
      resources :tasks   do
        put :st, as: 'st'
        put :sti, as: 'sti'
        put :ust, as: 'ust'
        put :usti, as: 'usti'
      end 
    end
  end 
end
  

  

end

app/models/todopage.rb
class Todopage < ActiveRecord::Base
  belongs_to :todosection
  has_many :tasks, dependent: :destroy
  validates :title, presence: true
  validates :todosection_id, presence: true
  

end

app/controllers/todopages_controller.rb
class TodopagesController < ApplicationController
  def index
    @todopages = Todopage.where(todosection_id: @todosection.id)
  end
  def show
    @todosection = Todosection.find(params[:todosection_id])
    @todopages = Todopage.where(todosection_id: @todosection.id)
    @todopage = Todopage.find(params[:id])
  end
  def new
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.new(todopage_params)
    @todopage.todosection_id = @todosection.id
    render 'new'
  end

  def create
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.new(todopage_params)
    @todopage.todosection_id = @todosection.id
    if @todopage.save
      redirect_to @todosection
    else
      @error=t("Title can't be blank")
      render 'new'
    end
  end

  def edit
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:id])
  end

  def update
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = Todopage.find(params[:id])
    @todopage.update_attributes(todopage_params)
    if @todopage.update(todopage_params)
      redirect_to  @todosection
    else
      @error=t("Title can't be blank")
      render 'edit'
    end
  end
  
  def destroy
    @todosection = Todosection.find(params[:todosection_id])
    @todopage = @todosection.todopages.find(params[:id])
    @todopage.destroy
    redirect_to todosection_path(@todosection)
  end

  private
    def todopage_params
      params.require(:todopage).permit(:title)
    end
end

app/helpers/todopages_helper.rb
module TodopagesHelper
end

app/views/todopages/_form.html.haml
= form_for([@todosection, @todosection.todopages.build]) do |f|
  %p
    = f.label I18n.t("Title Pages")
    = f.text_field :title
    %br
    = f.submit I18n.t("Create")

app/views/todopages/_todopage.html.haml
.page
  %table
    %tr#head
      %td
      %td
        #title 
          #{todopage.title}
          = link_to image_tag("ed.png", :border => 0),  edit_todosection_todopage_path(@todosection,[todopage])
          = link_to image_tag("del.png", :border => 0),  [todopage.todosection, todopage],  method: :delete, data:  { confirm: I18n.t("Are you sure?") }    
      %td
      %td
      %td
    %th#chek 
      =I18n.t("Executed")
    %th#name 
      =I18n.t("Title")
    %th#urgency 
      =I18n.t("Urgently")
    %th#date 
      =I18n.t("Execute Until")
    %th#hrefs 

  = render todopage.tasks
  
  %br
  = form_for([@todosection, todopage, todopage.tasks.build]) do |f|
    = f.text_field :title,:style => 'border:1px #6699CC solid ;width: 83%;margin: 1%', placeholder: I18n.t("Title Task")
    .btn.btn-primary
      = f.submit I18n.t("Add")
  %br
%br

app/views/todopages/edit.html.haml
.e_form
  #title
    =t("EditP")
    %br
    =t("Pagee")
  = form_for :todopage, url: todosection_todopage_path, method: :patch do |f|
    - if @todopage.errors.any?
      #error_explanation
        = @error
    %p
      = f.label I18n.t("Title Page")
      = f.text_field :title
      %br
      = f.submit I18n.t("Update")
  %br
  %space <-
  = link_to I18n.t("Back"),@todosection

app/views/todopages/new.html.haml
.e_form
  #title
    =t("New Page")
  - if @todopage.errors.any?
    #error_explanation
      = @error
  = render 'form'
  %br
  %space <-
  = link_to I18n.t("Back to Section"), @todosection

app/views/todopages/show.html.haml
%br
%br
%br
.page
  %table
    %tr#head
      %td
      %td
        #title 
          = link_to image_tag("comeback.png", :border => 0),@todosection
          #{@todopage.title}
          = link_to image_tag("ed.png", :border => 0),  edit_todosection_todopage_path(@todosection,[@todopage])
          = link_to image_tag("del.png", :border => 0),  [@todopage.todosection, @todopage],  method: :delete, data:  { confirm: I18n.t("Are you sure?") }    
      %td
      %td
      %td
    %th#chek Выполнен
    %th#name Название
    %th#urgency Срочно
    %th#date Выполнить до
    %th#hrefs Ссылки

  = render @todopage.tasks
  
  %br
  = form_for([@todosection, @todopage, @todopage.tasks.build]) do |f|
    = f.text_field :title,:style => 'border:1px #6699CC solid ;width: 83%;margin: 1%', placeholder: I18n.t("Title Task")
    .btn.btn-primary
      = f.submit I18n.t("Add")
  %br
%br